### ISSUE TITLE
It doesn't display the chart

### ISSUE THREAD

**Issue by Minimona** [NuCOS/angular-bokeh#1]
Hi,

I would appreciate your help, because I'm using the first time angular and bokeh.

When I start the app.py the browser display the 

"Welcome to bokeh-app! 
Angular-Logo
This is the embeded bokeh chart component:"

but not more. This is the bokeh tag:

`<bokeh-chart _ngcontent-mxv-c0="" _nghost-mxv-c1=""><div _ngcontent-mxv-c1="" id="3099" class="bk-root"></div></bokeh-chart>`

And thats the errors and warnings:

`[bokeh] JS/Python version mismatch
P.from_json @ bokeh-1.0.4.min.js:31
l @ bokeh-1.0.4.min.js:31
(anonymous) @ bokeh-1.0.4.min.js:31
requestAnimationFrame (async)
i.defer @ bokeh-1.0.4.min.js:31
i.embed_item @ bokeh-1.0.4.min.js:31
push../src/app/shared/services/bokeh.service.ts.BokehService.plot @ bokeh.service.ts:29
push../src/app/core/services/message.service.ts.MessageService.manageMsg @ message.service.ts:107
(anonymous) @ message.service.ts:57
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:192
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next @ Subscriber.js:130
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ Subscriber.js:76
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:53
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ Subscriber.js:76
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:53
push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next @ Subject.js:47
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ Subscriber.js:76
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:53
push../node_modules/rxjs/_esm5/internal/operators/map.js.MapSubscriber._next @ map.js:41
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:53
wrapFn @ zone.js:1332
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:423
onInvokeTask @ core.js:17290
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:422
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:195
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:498
invokeTask @ zone.js:1744
globalZoneAwareCallback @ zone.js:1770
bokeh-1.0.4.min.js:31 [bokeh] Library versions: JS (1.0.4) / Python (1.1.0)`

and 

`Uncaught Error: property Plot.center wasn't declared
    at t.c.setv (bokeh-1.0.4.min.js:31)
    at t.c [as constructor] (bokeh-1.0.4.min.js:31)
    at t.i [as constructor] (bokeh-1.0.4.min.js:31)
    at t [as constructor] (bokeh-1.0.4.min.js:31)
    at new t (bokeh-1.0.4.min.js:31)
    at Function.P._instantiate_object (bokeh-1.0.4.min.js:31)
    at Function.P._instantiate_references_json (bokeh-1.0.4.min.js:31)
    at Function.P.from_json (bokeh-1.0.4.min.js:31)
    at l (bokeh-1.0.4.min.js:31)
    at bokeh-1.0.4.min.js:31`

and 

`Source-Map-Fehler: request failed with status 404
Ressourcen-Adresse: https://cdn.pydata.org/bokeh/release/bokeh-1.0.4.min.js
Source-Map-Adresse: bokeh.min.js.map`

I don't know what I have to do :s 
I tried to update bokeh and angular, but it seems to be getting worse.

Thanks!

**Comment by DocBO** [comment]
Hi,

I have updated the project to bohek 1.1.0. Be sure that your python module bokeh is of the same version number. 

To reinstall remove the node_modules folder in client and start again: *npm install*

Be sure to delete the browser history after rebuild, to make sure the browser is also updating the app.
 
I also changed some minor details in the interface, now it is more like it should be in angular.
