### ISSUE TITLE
Getting only empty page without chart

### ISSUE THREAD

**Issue by chetanambi** [NuCOS/angular-bokeh#2]
Hi - I followed the exact steps mentioned in the instructions but getting just an empty screen with heading and Angular logo as shown below. 

There are no errors the but in the command line, I can see only this information. Do you have any suggestions?

```
(angular-bokeh) C:\Users\ambi\Desktop\angular-bokeh-master\python>python app.py
[2021-05-26 17:16:30,953]              INFO     -- start server on localhost port 9000
[2021-05-26 17:16:30,954]              INFO     -- path: C:\Users\ambi\Desktop\angular-bokeh-master\python\../client/dist/dev
[2021-05-26 17:16:35,944] PythonToView INFO     -- from angular: {"name":"addChart","args":["7684","plot"],"action":"default","user":"8049"}
0.031836509704589844
```

![image](https://user-images.githubusercontent.com/37707687/119654743-64057700-be46-11eb-8bdc-1011c3caf503.png)

**Comment by DocBO** [comment]
Hi, I updated to angular 10, bokeh 2.3.2 and python3.8
I think the issue was inconsistent versions of bokeh.

Please remove all artefacts for the client (e.g. the folder node_modules) and start rebuild.
```
npm install
ng build
```

**Comment by chetanambi** [comment]
Thanks a lot for the quick response! I was able to get the graph now. Though I am not able to see it fully I can manage to handle this myself. Thank again for providing this example. This is really helpful. 

I am closing this as the issue is resolved. 

![image](https://user-images.githubusercontent.com/37707687/119678754-6a531d80-be5d-11eb-908d-65cc4ac48596.png)
