### ISSUE TITLE
Bokeh rendering without CDN

### ISSUE THREAD

**Issue by sammaphey** [NuCOS/angular-bokeh#5]
I have already solved this but wanted a way to present to others who may be in the same boat.

If you are running with Angular outside of a cdn (bad internet access, etc.) then you should use `npm install` to add the bokeh library.

Everything else in this example stays the same with the following exceptions:

- Add bokeh via npm: `npm i @bokeh/bokehjs --save`
- Update your `angular.json` file to contain the following in the `scripts` section:
```javascript
"scripts": [
    ...
    "node_modules/@bokeh/bokehjs/build/js/bokeh.min.js"
    ...
]
```

**Comment by skidzo** [comment]
Thanks for the hint, i will also mention this in the wiki!
